import { Comic } from './types';

const GENRES = ['Action', 'Adventure', 'Fantasy', 'System', 'Regression', 'Martial Arts', 'Drama', 'Comedy', 'Romance', 'School Life'];

const generateChapters = (count: number, prefix: string): any[] => {
  return Array.from({ length: count }, (_, i) => ({
    id: `${prefix}-ch-${count - i}`,
    number: `${count - i}`,
    title: `Episode ${count - i}`,
    releaseDate: new Date(Date.now() - i * 86400000).toISOString().split('T')[0] // sequential dates
  }));
};

export const MOCK_COMICS: Comic[] = [
  {
    id: '1',
    title: 'Solo Leveling: Arise',
    slug: 'solo-leveling-arise',
    description: 'In a world where hunters, humans who possess magical abilities, must battle deadly monsters to protect the human race from certain annihilation, a notoriously weak hunter named Sung Jinwoo finds himself in a seemingly endless struggle for survival.',
    coverUrl: 'https://picsum.photos/seed/solo/300/450',
    rating: 9.8,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'Chugong',
    artist: 'DUBU',
    genres: ['Action', 'Adventure', 'Fantasy', 'System'],
    chapters: generateChapters(189, 'sl'),
    isHot: true,
  },
  {
    id: '2',
    title: 'The Return of the Mount Hua Sect',
    slug: 'return-mount-hua',
    description: 'Chung Myung, the 13th Disciple of the Mount Hua Sect, one of the 3 Great Swordsmen, Plum Blossom Sword Saint, defeated Chun Ma, who has brought destruction and disarray onto the world. After the battle, he breathes his last breath on top of the headquarters of the Heavenly Demon Sect.',
    coverUrl: 'https://picsum.photos/seed/hua/300/450',
    rating: 9.9,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'Biga',
    artist: 'LICO',
    genres: ['Martial Arts', 'Comedy', 'Adventure', 'Regression'],
    chapters: generateChapters(120, 'rmh'),
    isHot: true,
  },
  {
    id: '3',
    title: 'Omniscient Reader’s Viewpoint',
    slug: 'orv',
    description: 'Dokja was an average office worker whose sole interest was reading his favorite web novel "Three Ways to Survive the Apocalypse." But when the novel suddenly becomes reality, he is the only person who knows how the world will end.',
    coverUrl: 'https://picsum.photos/seed/orv/300/450',
    rating: 9.7,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'SingNsong',
    artist: 'Sleepy-C',
    genres: ['Action', 'Fantasy', 'System', 'Apocalypse'],
    chapters: generateChapters(210, 'orv'),
    isHot: true,
  },
  {
    id: '4',
    title: 'The Beginning After The End',
    slug: 'tbate',
    description: 'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power.',
    coverUrl: 'https://picsum.photos/seed/tbate/300/450',
    rating: 9.6,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'TurtleMe',
    artist: 'Fuyuki23',
    genres: ['Action', 'Adventure', 'Fantasy', 'Isekai'],
    chapters: generateChapters(175, 'tbate'),
    isHot: false,
    isNew: true,
  },
  {
    id: '5',
    title: 'Reaper of the Drifting Moon',
    slug: 'reaper-moon',
    description: 'He’s in the deepest part of the Jianghu. Keep your eyes wide open if you don’t want to be dragged into the abyss.',
    coverUrl: 'https://picsum.photos/seed/reaper/300/450',
    rating: 9.5,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'Woo-Gak',
    artist: 'INKY',
    genres: ['Action', 'Martial Arts', 'Drama'],
    chapters: generateChapters(85, 'rdm'),
    isHot: true,
  },
  {
    id: '6',
    title: 'Nano Machine',
    slug: 'nano-machine',
    description: 'Cheon Yeo-Woon, an illegitimate child of the Demonic Cult, receives a surprise visit from his descendant from the future who inserts a nano machine into Cheon Yeo-Woon’s body.',
    coverUrl: 'https://picsum.photos/seed/nano/300/450',
    rating: 9.4,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'Han-Joong-Wueol-Ya',
    artist: 'Geum-Gang-Bul-Gae',
    genres: ['Action', 'Martial Arts', 'Sci-Fi'],
    chapters: generateChapters(150, 'nm'),
  },
  {
    id: '7',
    title: 'SSS-Class Suicide Hunter',
    slug: 'sss-suicide',
    description: 'I want an S-Rank skill too! I want it so badly, I could die for it! [You have awakened an S-Rank skill.] [But it only works when you die.]',
    coverUrl: 'https://picsum.photos/seed/sss/300/450',
    rating: 9.8,
    status: 'Ongoing',
    type: 'Manhwa',
    author: 'Shin Noah',
    artist: 'Bill K',
    genres: ['Action', 'Fantasy', 'Tower', 'Regression'],
    chapters: generateChapters(110, 'sss'),
  },
  {
    id: '8',
    title: 'Legend of the Northern Blade',
    slug: 'northern-blade',
    description: 'When the world was plunged into darkness by the Silent Night, martial artists gathered to form the Northern Heavenly Sect.',
    coverUrl: 'https://picsum.photos/seed/lnb/300/450',
    rating: 9.9,
    status: 'Completed',
    type: 'Manhwa',
    author: 'Woo-Gak',
    artist: 'Hae-Min',
    genres: ['Action', 'Martial Arts', 'Revenge'],
    chapters: generateChapters(160, 'lnb'),
  }
];

export const POPULAR_TODAY = MOCK_COMICS.filter(c => c.isHot);
export const LATEST_UPDATES = MOCK_COMICS;
